name: production-deploy
run-name: ${{ github.actor }} has triggered the pipeline for Production

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        env:
            MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
            MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
            DEPLOY_BUCKET: ${{ vars.DEPLOY_BUCKET_PRODUCTION }}

            # Terraform env vars are lowcase by project convention
            TF_VAR_db_password: ${{ secrets.DB_PASSWORD_PRODUCTION }}
            TF_VAR_project_id: ${{ vars.PROJECT_ID_PRODUCTION }}
            TF_VAR_atlas_org_id: ${{ vars.ATLAS_ORG_ID }}
            TF_VAR_db_user: 'gcp-ms'
            TF_VAR_db_instance_name: 'gcp-ms-prod'
            TF_VAR_atlas_project_name: 'gcp-ms-prod'
        steps:
            # Checkout code form repo
            - name: 'Checking out code...'
              uses: actions/checkout@v4

            # Generate backend.tf file
            - name: 'Generating backend.tf file...'
              run: chmod a+rx .deploy/backend.tf.sh && ./.deploy/backend.tf.sh

            - name: 'backend.tf'
              run: cat backend.tf

            # Login to GCP
            - name: 'Logging in to GCP...'
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  workload_identity_provider: ${{ vars.GCP_MS_IDP_PRODUCTION }}
                  create_credentials_file: true
                  service_account: ${{ vars.GCP_MS_SVC_ACCT_PRODUCTION }}
                  token_format: 'access_token'
                  access_token_lifetime: '120s'

            # Terraform steps
            - name: 'Settign up Terraform...'
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.9
                  terraform_wrapper: true
            - name: 'Terraform init...'
              id: init
              run: terraform init
            - name: 'Terraform Format...'
              id: fmt
              run: terraform fmt -recursive -write=true
            - name: 'Terraform validate...'
              id: validate
              run: terraform validate
            - name: 'Terraform plan...'
              id: plan
              run: terraform plan
              continue-on-error: true
            - name: 'Terraform Plan Status...'
              if: steps.plan.outcome == 'failure'
              run: exit 1
            - name: 'Terraform apply...'
              run: terraform apply -auto-approve
